# 设置项目名称
spring:
  application:
    name: street
  # 配置日期格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  # 配置数据源
  datasource:
    # mysql用户名
    username: root
    # 密码
    password: 123456
    # 链接地址
    url: jdbc:mysql://localhost:3306/street?serverTimezone=GMT%2B8
    # mysql连接驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
  # banner作者
  author: kai
  # redis配置
  redis:
    # 使用第一个数据库
    database: 0
    # IP地址
    host: localhost
    # 端口号
    port: 6379
    # 超时时间
    timeout: 10000ms
    # 对象池配置
    lettuce:
      pool:
        # 最大连接数
        max-active: 1024
        # 空闲最小连接数
        min-idle: 5
        # 最大等待时间
        max-wait: 10000ms
        # 空闲最大连接数
        max-idle: 200

# 配置端口号
server:
  port: 9002

  servlet:
    context-path: /street

# 配置MyBatis扫描目录
mybatis:
  mapper-locations: classpath:mapper/*xml
  # Mybatis扫描包
  type-aliases-package: com.entity
  configuration:
    # 是否开启驼峰转换
    map-underscore-to-camel-case: true
    # 控制台打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# jwt配置
jwt:
  # 请求头
  tokenHeader: Authorization
  # 签名加盐
  secret: iwqjhda8232bjgh432
  #JWT过期时间(60*60*24*30)  一个月
  expiration: 18144000
  # token头部
  tokenHead: 'Bearer '


# 微信小程序
wx:
  appid:
  secret:

exchange-rate: 1